#!/usr/bin/env python

import rospy
from mavgnc.mavgnc_mission_square import MavGNCMissionSquare

if __name__ == '__main__':
    rospy.init_node('squre', anonymous=True)
    mission_square = MavGNCMissionSquare()
    mission_square.run()

