#!/usr/bin/env python

import rospy
from mavgnc.mavgnc_position_control import  MavGNCPositionControl

if __name__ == '__main__':
    rospy.init_node('position_ctrl', anonymous=True)
    pos_ctrl = MavGNCPositionControl()
    pos_ctrl.run()

